server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: dio-digital-bank
  data:
    mongodb:
      uri: mongodb://localhost:27017/dio-digital-bank
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher